---
# tasks file for common
- name: install packages
  apt: name={{item}} state=present
  with_items:
       - git
       - mc
       - python-pip

- name: Install docker-py
  become: true
  pip:
    name: docker-py
    state: present

- name: Ensure docker is started
  service:
    name: docker
    state: started