---
# tasks file for common
- name: apt update
  apt:
    update_cache: yes

- name: packages tools present
  apt: name={{item}} state=present
  with_items:
     - python3-pip
     - mc

- name: inst requests
  become: true
  pip:
    name: requests
    executable: pip3

- name: inst docker-py
  become: true
  pip:
    name: docker-py
    state: present

- name: inst apt docker is present
  apt:
    name: docker.io
    state: present

- name: Ensure docker is started
  service:
    name: docker
    state: started