---
# tasks file for building
- name: Copy Dockerfile into build node
  copy: src=Dockerfile dest={{ dest_folder_git }}

- name: Build image
  docker_image:
    path: {{ dest_folder_git }}
    name: dz9
    tag: latest

- name: Tag image with Docker Hub repository name
  docker_image:
    name: dz9
    tag: latest
    repository: trsverre/dz9
    push: yes