---
# tasks file for webserver
- name: Pull Docker image from Docker Hub
  docker_image:
    name: trsverre/dz9
    tag: 1
- name: Started Docker container 
  become: true
  docker_container:
    name: prod
    image: trsverre/dz9:1
    state: started
    ports:
      - "8000:8080"      